name: 'example'
description: "Example application for the automated testing framework's desktop plugin"
publish_to: 'none'
version: '1.0.0+16'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.7+4'
  automated_testing_framework_example: '^2.2.5'
  automated_testing_framework_plugin_desktop: 
    path: '..'
  flutter: 
    sdk: 'flutter'
  logging: '^1.1.0'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.1'

flutter: 
  uses-material-design: true
  assets: 
    - 'assets/tests/'
    - 'assets/all_tests.json'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
