name: 'example'
description: "Example application for the automated testing framework's desktop plugin"
publish_to: 'none'
version: '1.0.0+7'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+8'
  automated_testing_framework_example: '^2.2.4+9'
  automated_testing_framework_plugin_desktop: 
    path: '..'
  flutter: 
    sdk: 'flutter'
  logging: '^1.0.2'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.1'

flutter: 
  uses-material-design: true
  assets: 
    - 'assets/tests/'
    - 'assets/all_tests.json'
