name: 'automated_testing_framework_plugin_desktop'
description: 'Library to use provide desktop related functions.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_desktop'
version: '2.0.0+18'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.7+5'
  desktop_window: '^0.4.0'
  flutter: 
    sdk: 'flutter'
  json_class: '^2.1.2+11'
  static_translations: '^2.1.1+14'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
